app:
  name: 'Product Default'
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:55001/product'
    username: appuser
    password: '{cipher}93386b1c11e97618e6b35273257989fc7afe0504c49427631750f6ce90d04c44'
    driver-class-name: org.postgresql.Driver